<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sign_in_btn</name>
   <tag></tag>
   <elementGuidId>edec6c41-7a4e-45b9-9886-d78c6dfce2f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_customized_sign_in</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@type=&quot;submit&quot; and @value=&quot;Sign in&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>249dfafa-f67d-43e4-956b-8b7ae67645dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>34eb1948-5d76-45f7-91bf-0f1cfe68277a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>a5dd354a-ee4e-4c46-99b4-84f67dd0b8df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3026f165-96d9-4c08-bca4-8cd75ec40084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-expression:value</name>
      <type>Main</type>
      <value>screenset.translations['HEADER_131443300282291300_LABEL']</value>
      <webElementGuid>b3dbf534-58ba-473b-a829-e1bdd4ac4963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-input-submit</value>
      <webElementGuid>552edd2a-58cc-4320-b0ad-77cebfc61cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>btn_customized_sign_in</value>
      <webElementGuid>9b3d6ed4-e39c-42ab-b9e9-e3e345b4390c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3bf4703d-d34a-40c9-8cfd-3fce9af5319f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>c84a71be-bf49-42be-a619-f113d3572371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_customized_sign_in</value>
      <webElementGuid>7296e9db-01f0-4902-b0bf-f548638d32db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>b29feb1d-a3d1-4b4d-b237-14ac8b984bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_customized_sign_in&quot;)</value>
      <webElementGuid>30375fec-33a5-4000-bc67-e2762c4c51b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_customized_sign_in']</value>
      <webElementGuid>b8cdbfc1-aa7f-4afa-ac55-b2671603ed05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-login-form']/div[2]/div/div[3]/input</value>
      <webElementGuid>56b72862-6829-4036-80d4-657324a48770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>bb34176c-8b3f-46d6-9ad0-eea26918deb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'btn_customized_sign_in']</value>
      <webElementGuid>f87acd60-4c25-46a6-90b1-324495417aab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
