<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pizza</name>
   <tag></tag>
   <elementGuidId>4688d92f-1fd8-41bf-aa6c-9549b625d51c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/img[@alt=&quot;Pizza&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>d4b8eb50-31d1-4caa-b1dc-19dc0573ae51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pizza</value>
      <webElementGuid>8e1b90fa-51a5-456b-9f66-28c61990b56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;App&quot;)/main[@class=&quot;MenuPage theme-dark&quot;]/div[@class=&quot;full-site-width&quot;]/section[@class=&quot;Section&quot;]/div[@class=&quot;MenuPage__wrapper d-flex flex-wrap&quot;]/div[@class=&quot;MenuPage__link text-center text-capitalize px-2 px-lg-0 mb-4 last-row-center-item&quot;]/a[@class=&quot;link d-block&quot;]/h2[1]</value>
      <webElementGuid>56b6e3c8-6895-4459-b78c-235005f4ee9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='App']/main/div/section[2]/div/div/a/h2</value>
      <webElementGuid>d7e2e58f-672c-464a-bc83-8bb047f1d22b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[2]/following::h2[1]</value>
      <webElementGuid>3a417510-aa5c-475a-a390-3f10de202c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::h2[1]</value>
      <webElementGuid>36d41cf4-2a0e-48df-94f5-e30fdd8a9b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apps &amp; Sides'])[1]/preceding::h2[1]</value>
      <webElementGuid>ab0a3e96-ffaf-4214-b1df-0b436105574a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chips &amp; Snacks'])[1]/preceding::h2[2]</value>
      <webElementGuid>4cc8726c-877a-4d44-9f77-2e298d8061ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pizza']/parent::*</value>
      <webElementGuid>cff5ea91-5ce7-40aa-8363-a28a003c5dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>32aa4209-3535-4a44-b683-bceb9d9fb186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Pizza' or . = 'Pizza')]</value>
      <webElementGuid>1f5be04a-97db-4706-89ee-ddaac127e038</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
