<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pickup Pickup</name>
   <tag></tag>
   <elementGuidId>65d4f1b6-c0b3-4428-8d21-dbae5073d845</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-secondary.btn-secondary--chunky.position-relative</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4de8a3df-c257-4748-a3ad-d8fdb624b6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>carryout</value>
      <webElementGuid>71f16207-f042-4391-a5ee-aba4e2fef918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a80aca8c-effc-4d38-83b6-2a010c1b6ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary btn-secondary--chunky position-relative</value>
      <webElementGuid>6fc8ead2-8f54-42a6-ab11-2cec7b84d823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pickup Pickup</value>
      <webElementGuid>9a23e941-16e6-4898-a11a-104d5f9cc498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;App&quot;)/section[@class=&quot;OrderFlow&quot;]/div[@class=&quot;InitiateOrder mobile-phase-1&quot;]/div[@class=&quot;InitiateOrder__actions-container&quot;]/div[@class=&quot;full-site-width h-100 d-flex&quot;]/div[@class=&quot;InitiateOrderAction&quot;]/div[@class=&quot;InitiateOrderAction__inactive&quot;]/div[@class=&quot;InitiateOrderAction__inactive_btn&quot;]/button[@class=&quot;btn btn-secondary btn-secondary--chunky position-relative&quot;]</value>
      <webElementGuid>3a21ded3-e245-41c6-b316-7a53d42cdd4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>83382bd5-2793-4cfb-b33a-c269319df960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='App']/section/div[2]/div/div[2]/div/div/div/button</value>
      <webElementGuid>d502d5ab-57b1-41c4-936e-d820d8b7d35c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[2]/following::button[1]</value>
      <webElementGuid>f73b03de-1a62-45d8-b9aa-1cc4f89d1963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact us'])[1]/following::button[1]</value>
      <webElementGuid>92c823d2-c9ce-4691-8c54-725656a10b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>c0b3d7c1-1940-4b64-b117-6bcb4324ed10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Pickup Pickup' or . = 'Pickup Pickup')]</value>
      <webElementGuid>6418bec7-783d-4a10-8fd3-ac171a521c75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
