<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your delivery address_address</name>
   <tag></tag>
   <elementGuidId>c3ad5c1d-9a45-4af5-ba80-8340e74d25ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;address&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4202726e-f80f-4435-af9b-889a3cc71748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>addressSearchField</value>
      <webElementGuid>a41eaca7-5dc1-48ad-8574-0a03db35c2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your location</value>
      <webElementGuid>b7761727-b78c-4698-87be-a3cd7bfe347a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6b335227-8cfa-469e-b766-06e660ec2f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>87594c65-ab1c-4b97-8df3-1ed528d181a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>62f2ffcb-ce82-47e3-accb-add6f9336844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f2108324-762d-49ad-b49d-f4b05ef121af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextField form-control pac-target-input</value>
      <webElementGuid>673b30f6-c566-4b47-8c8b-b37d97fc5b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;App&quot;)/section[@class=&quot;OrderFlow&quot;]/div[@class=&quot;InitiateOrder mobile-phase-3&quot;]/div[@class=&quot;InitiateOrder__actions-container&quot;]/div[@class=&quot;full-site-width h-100 d-flex&quot;]/div[@class=&quot;InitiateOrderAction is-active focused&quot;]/div[@class=&quot;InitiateOrderAction__active&quot;]/div[@class=&quot;InitiateOrderAction__search_transition&quot;]/div[@class=&quot;AddressField&quot;]/input[@class=&quot;TextField form-control pac-target-input&quot;]</value>
      <webElementGuid>e8e33ea0-7aa0-4e1f-ac25-41b666fef8fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='address']</value>
      <webElementGuid>a12e6741-73fb-4de9-bd32-40755b15ddbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='App']/section/div[2]/div/div[2]/div/div/div[3]/div/input</value>
      <webElementGuid>51672533-0da3-4c71-8a40-dd6e94bdca9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>9a2399aa-2495-4acd-8895-313f25c7e8e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter your location' and @name = 'address' and @type = 'text']</value>
      <webElementGuid>d04c0e89-e82b-49c3-b0b9-edd19a8bbe5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
