<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Start Order_1</name>
   <tag></tag>
   <elementGuidId>bafc926b-3523-4b4b-9905-ec6190d5d81f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.position-relative</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='App']/section/div[2]/div[2]/div/div/div/div/div/div/div[2]/div/div/div/div[3]/form/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4ca41a53-b06b-44f0-a654-f24e4c392d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>position-relative</value>
      <webElementGuid>7d47a88a-37b9-4a11-89d1-be6da118f2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start Order</value>
      <webElementGuid>7380d26a-1c14-4af1-ace0-d9bfab8d1e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;App&quot;)/section[@class=&quot;OrderFlow&quot;]/div[@class=&quot;InitiateOrder mobile-phase-3&quot;]/div[@class=&quot;InitiateOrder__stores-container theme-light&quot;]/div[@class=&quot;InitiateOrder__stores-container_inner&quot;]/div[@class=&quot;w-100 h-100&quot;]/div[@class=&quot;StoreSelection&quot;]/div[@class=&quot;StoreSelection__store-results px-2 px-sm-3 px-md-5&quot;]/div[@class=&quot;StoreSelection__store-results_list d-sm-flex flex-column pr-sm-2&quot;]/div[@class=&quot;StoreSelection__store-results_list_stores flex-sm-grow-1&quot;]/div[2]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;RetailStore&quot;]/div[@class=&quot;StoreCard&quot;]/div[@class=&quot;StoreCardRow p-2 StoreCardRow__selection&quot;]/form[1]/button[@class=&quot;btn btn-primary w-100&quot;]/span[@class=&quot;position-relative&quot;]</value>
      <webElementGuid>ec5610df-ac2d-4c57-9ebe-e05e187e4df0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='App']/section/div[2]/div[2]/div/div/div/div/div/div/div[2]/div/div/div/div[3]/form/button/span</value>
      <webElementGuid>3a4c50f3-44b8-4e89-b71c-439b63143114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Est. Time:'])[1]/following::span[1]</value>
      <webElementGuid>e248eb64-232a-42c9-925a-4b7a8bcacf52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='When would you like your order?'])[1]/following::span[1]</value>
      <webElementGuid>52f317b4-a760-47b8-bdb6-f11a0135b350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[7]/preceding::span[1]</value>
      <webElementGuid>c28303cf-65bf-456c-99b0-7cbd54e34d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[8]/preceding::span[1]</value>
      <webElementGuid>0dde2706-4ac8-433b-83db-dc29f8271931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Start Order']/parent::*</value>
      <webElementGuid>5f0af471-8e75-4ccc-948d-b92bd6b6c159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button/span</value>
      <webElementGuid>8f8b7748-ef42-46bd-af8d-baed9cd31339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Start Order' or . = 'Start Order')]</value>
      <webElementGuid>a21b7a5c-5219-4838-9b5f-894ae9176a0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
