<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Sausage Pizza_FoodItemTypeSelector33</name>
   <tag></tag>
   <elementGuidId>4c9e6211-627f-47ad-8fe3-294a2e19614b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FoodItemTypeSelector33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='FoodItemTypeSelector33']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5dc591a6-c147-4752-837a-f0440d97185e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>FoodItemTypeSelector</value>
      <webElementGuid>02889332-f524-4f2b-8360-ad1b0aaa3d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FoodItemTypeSelector33</value>
      <webElementGuid>14b9d9b8-1f10-4590-9d5b-a59a14f1de3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Select__inp</value>
      <webElementGuid>3e568337-1e90-4f42-80e9-b6de9b5e606f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FoodItemTypeSelector33&quot;)</value>
      <webElementGuid>bddc5e3b-ef99-49ae-9b07-a4c5eeb5fa03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='FoodItemTypeSelector33']</value>
      <webElementGuid>b409b631-196b-4328-b15c-0728bfb51d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='App']/main/div/section/div/div[2]/div/div[2]/div/label/select</value>
      <webElementGuid>689199d3-e998-4869-96b1-00f3e57ea2a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sausage Pizza'])[2]/following::select[1]</value>
      <webElementGuid>908b5e8d-8b24-4293-b547-f3fb41fdcefb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sausage Pizza'])[1]/following::select[1]</value>
      <webElementGuid>5b5d1c5a-c31c-4d17-ac1c-61448abfba4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[1]/preceding::select[2]</value>
      <webElementGuid>21718d7e-3a1e-4664-9660-20bcc6ef1a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>85f98693-198a-42bc-896f-07cc360630d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'FoodItemTypeSelector33']</value>
      <webElementGuid>0bb74fab-d6d2-4261-a859-b7a529ff8732</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
