<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>6eacdf5d-d232-4b6a-8efb-367015291a31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.px-25.GA_addToOrder_Links</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='App']/main/div/section/div/div[2]/div/div[3]/div/button/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>095df380-d0fa-4e82-bea5-8eda35d7ed2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-25 GA_addToOrder_Links</value>
      <webElementGuid>5210bb50-7398-48da-b1eb-8f11a59f8d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>|</value>
      <webElementGuid>b3456b3f-c5eb-4360-a1ee-ddc40802cb20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;App&quot;)/main[@class=&quot;ProductDetailPage ProductDetailPage--customizer theme-dark has-fixed-footer&quot;]/div[@class=&quot;full-site-width&quot;]/section[@class=&quot;Section&quot;]/div[@class=&quot;ProductDetailPage__selector-container row&quot;]/div[@class=&quot;col-8 col-sm-6&quot;]/div[@class=&quot;FoodItem FoodItem--customizer&quot;]/div[@class=&quot;d-none d-sm-flex&quot;]/div[@class=&quot;d-none d-sm-block&quot;]/button[@class=&quot;btn btn-primary FoodItem__mobile-footer_btn&quot;]/span[@class=&quot;position-relative&quot;]/span[@class=&quot;px-25 GA_addToOrder_Links&quot;]</value>
      <webElementGuid>64c3d3a9-af25-4b72-8cb5-0cd65b55a3e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='App']/main/div/section/div/div[2]/div/div[3]/div/button/span/span[2]</value>
      <webElementGuid>c5cf627e-703b-4372-90eb-5c98f88aab4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[1]/following::span[1]</value>
      <webElementGuid>fa651edc-09b4-4038-ad2c-693081bef506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Sausage Pizza'])[1]/preceding::span[1]</value>
      <webElementGuid>b429da80-4e88-4025-a1d7-15b7a1a60acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='|']/parent::*</value>
      <webElementGuid>b2d05b1a-541f-434c-9f8c-b8bedfa89818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span/span[2]</value>
      <webElementGuid>fcd75f48-2b9c-46b5-9e23-8f01fc9173fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '|' or . = '|')]</value>
      <webElementGuid>e05c2bea-00d8-4a2c-8e71-831e49c36179</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
