<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address_TextBar</name>
   <tag></tag>
   <elementGuidId>258bb330-3b23-4ef0-a809-13b07cb6a8b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;address&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5912def-bae3-47e2-aae7-98a43c1bb660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>addressSearchField</value>
      <webElementGuid>9a338b36-bebb-4927-bb65-155a59ca583d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your location</value>
      <webElementGuid>c614e35c-5b76-43cc-a4ec-8de8e33f2420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>065741c4-bea7-4246-bd05-3b0b36290110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>2bcc346a-291b-44c1-99fe-098f6f674fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>da1c8bd7-fb3f-4f66-b135-2eb02b863ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d9043d92-ce03-4119-b6aa-abc6d15b03a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextField form-control pac-target-input</value>
      <webElementGuid>f12d41f8-926d-460d-9f8e-2bc62adcda1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;App&quot;)/section[@class=&quot;OrderFlow&quot;]/div[@class=&quot;InitiateOrder mobile-phase-3&quot;]/div[@class=&quot;InitiateOrder__actions-container&quot;]/div[@class=&quot;full-site-width h-100 d-flex&quot;]/div[@class=&quot;InitiateOrderAction is-active focused&quot;]/div[@class=&quot;InitiateOrderAction__active&quot;]/div[@class=&quot;InitiateOrderAction__search_transition&quot;]/div[@class=&quot;AddressField&quot;]/input[@class=&quot;TextField form-control pac-target-input&quot;]</value>
      <webElementGuid>c523a0f6-1d53-406b-8312-2e7dc1782d7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='address']</value>
      <webElementGuid>c989b044-cb27-4e1d-ace9-1b8a2265b1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='App']/section/div[2]/div/div[2]/div/div/div[3]/div/input</value>
      <webElementGuid>158b0bc4-a9dd-4066-a591-3459bdc1c4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>f48a86e2-7188-4b33-a72c-b40f6fc17b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter your location' and @name = 'address' and @type = 'text']</value>
      <webElementGuid>ee37218f-eb02-45b2-979b-bd838caa91b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
