<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>date</name>
   <tag></tag>
   <elementGuidId>a833de26-c216-477d-8d77-8fc25070c998</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*/select[@data-automation-id=&quot;orderDateSelect&quot;])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
