<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pickup_occasion</name>
   <tag></tag>
   <elementGuidId>f7ae9e74-9027-4a6a-a32e-879d97a10dc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-secondary.btn-secondary--chunky.position-relative</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/button[@data-automation-id=&quot;carryout&quot; and @type=&quot;button&quot;][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>228bb803-5494-4233-84fe-117f7bf758f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>carryout</value>
      <webElementGuid>be9c23d4-c8c5-4b70-a768-5d6f98b609f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>175bcfca-02f8-480c-bc51-52b346016802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary btn-secondary--chunky position-relative</value>
      <webElementGuid>39f9279a-361b-4f8e-8a8a-fc91511f7338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pickup Pickup</value>
      <webElementGuid>aa00da9c-b585-438c-b8d1-5819026d288b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;App&quot;)/section[@class=&quot;OrderFlow&quot;]/div[@class=&quot;InitiateOrder mobile-phase-1&quot;]/div[@class=&quot;InitiateOrder__actions-container&quot;]/div[@class=&quot;full-site-width h-100 d-flex&quot;]/div[@class=&quot;InitiateOrderAction&quot;]/div[@class=&quot;InitiateOrderAction__inactive&quot;]/div[@class=&quot;InitiateOrderAction__inactive_btn&quot;]/button[@class=&quot;btn btn-secondary btn-secondary--chunky position-relative&quot;]</value>
      <webElementGuid>969866af-2301-4b75-9a5d-8f45577f7817</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>95cec516-1f06-42dd-9688-14ddc9a0250c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='App']/section/div[2]/div/div[2]/div/div/div/button</value>
      <webElementGuid>d4b59c1c-1b8c-49cf-b289-0a1c98a15041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[2]/following::button[1]</value>
      <webElementGuid>d61c1c60-7a45-4fd2-8d28-177fca2ecb4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact us'])[1]/following::button[1]</value>
      <webElementGuid>e06bca06-8de3-4ede-8444-23d79e567732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>74f7d2b2-9050-4f75-99c8-8b747b42e076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Pickup Pickup' or . = 'Pickup Pickup')]</value>
      <webElementGuid>f897b3ba-df55-4faa-aeb6-b7a9026a75c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
