<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkout BTN</name>
   <tag></tag>
   <elementGuidId>643cf57d-39e3-4679-801a-dee4b8a4d75b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[@data-automation-id=&quot;checkoutButton&quot;])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.link-btn-primary.w-100.GA_checkout_Links</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/cart/validateCartForNextStep' and (text() = ' Checkout
' or . = ' Checkout
')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>checkoutButton</value>
      <webElementGuid>221dab98-b8e0-4e21-b1ea-60799799465d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cart/validateCartForNextStep</value>
      <webElementGuid>5ce0c723-c4cd-4ff0-921f-bb0714785096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn link-btn-primary w-100 GA_checkout_Links</value>
      <webElementGuid>b656d71b-5a9e-49e8-997d-27ec785a078b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Checkout
</value>
      <webElementGuid>b1f007e8-f967-4d76-93a7-db9c55a30d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;App&quot;)/main[@class=&quot;CartPage theme-dark show-init-selected&quot;]/div[@class=&quot;full-site-width&quot;]/section[@class=&quot;Section&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-md-5 offset-md-2&quot;]/div[@class=&quot;CartLedger&quot;]/div[@class=&quot;CartFooter&quot;]/div[@class=&quot;CartFooter__static&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;CartFooterButtons__col&quot;]/a[@class=&quot;btn link-btn-primary w-100 GA_checkout_Links&quot;]</value>
      <webElementGuid>37cc7e7e-2a3b-4b47-aa32-0c553b9583dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>597d1058-5b7a-4d93-85bd-04c7225b7ec8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='App']/main/div[3]/section/div[2]/div[2]/div/div[5]/div/div/div[2]/a</value>
      <webElementGuid>40f3ba4d-2f9e-48e3-8400-2e9541954463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Checkout')]</value>
      <webElementGuid>a976c756-8c27-402a-a240-09083d51a45e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add More Items'])[1]/following::a[1]</value>
      <webElementGuid>9394c0f6-5283-4ebf-8c3e-10b13132611f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[9]/following::a[2]</value>
      <webElementGuid>1488f7b7-38f8-46c1-9f90-2df579580bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add More Items'])[2]/preceding::a[1]</value>
      <webElementGuid>6ba1be2e-d868-405b-b8cf-dfdaecd58e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[2]/preceding::a[2]</value>
      <webElementGuid>c65ee033-1ff1-41b5-b72f-86830e076af3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Checkout']/parent::*</value>
      <webElementGuid>c21e3fb4-e0f0-458c-b3a7-172f7fa4e823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cart/validateCartForNextStep')]</value>
      <webElementGuid>300475e7-a15e-4042-a1ac-890cb841ecdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/a</value>
      <webElementGuid>ba780bc6-4f05-4c00-b86d-5101b8d84cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cart/validateCartForNextStep' and (text() = ' Checkout
' or . = ' Checkout
')]</value>
      <webElementGuid>8d817054-f846-4bcc-b2be-0ba82d92e1ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='App']/main/div[3]/section/div[2]/div[2]/div/div[5]/div[2]/div/section/div/div/div/div[2]/a</value>
      <webElementGuid>ed667e16-83d7-48a2-8fed-ea5b4d8cec8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Checkout')])[2]</value>
      <webElementGuid>f93be23c-7bdd-4b1e-9e65-83ba179ce04c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add More Items'])[2]/following::a[1]</value>
      <webElementGuid>0954d7e5-08b8-4498-b4ac-bb3a71e97d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/following::a[2]</value>
      <webElementGuid>926215ab-2f7d-4c45-a939-5f38580333de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Careers'])[3]/preceding::a[6]</value>
      <webElementGuid>21014bc3-484b-40d0-883c-bb6acb8344ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Store positions'])[1]/preceding::a[7]</value>
      <webElementGuid>0b197489-2197-468a-935e-19db927d904a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/cart/validateCartForNextStep')])[2]</value>
      <webElementGuid>479d5ee1-2b17-432e-b54b-60e197d00625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/section/div/div/div/div[2]/a</value>
      <webElementGuid>2fc9f51f-d4d7-4384-9514-415469ecc8e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
