<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Sign in</name>
   <tag></tag>
   <elementGuidId>27dc1e4c-313a-434b-9dd9-e715e1268e83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.gigya-composite-control.gigya-composite-control-header.gigya-custom-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='gigya-login-form']/div[2]/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>cd7b4de9-4fb5-47b8-994a-145bc81e900b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-translation-key</name>
      <type>Main</type>
      <value>HEADER_131443300282291300_LABEL</value>
      <webElementGuid>490c3a7a-ab0a-4ca8-8913-3f2abfa4aef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-composite-control gigya-composite-control-header gigya-custom-header</value>
      <webElementGuid>94afe380-7982-46ef-8b88-53036260713f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>__gig_template_element_13_1689315153062</value>
      <webElementGuid>eec3a738-e9f4-49f0-a10f-650e0b266648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>97f879f7-c864-4fb0-95a3-f26889626b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>bc703e4a-3a32-4572-b055-152531bf5d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>04c64412-800a-4f91-9078-ad43d3ee56c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-login-form&quot;)/div[@class=&quot;gigya-layout-row with-divider&quot;]/div[@class=&quot;gigya-layout-cell responsive with-social-login&quot;]/h2[@class=&quot;gigya-composite-control gigya-composite-control-header gigya-custom-header&quot;]</value>
      <webElementGuid>da36e952-4a55-4fb9-9ab5-4d120e35e1b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-login-form']/div[2]/div/h2</value>
      <webElementGuid>48a9f29e-593f-4a64-96a6-479d2a76c56a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You`ve attempted to log in to a disabled account.'])[1]/following::h2[1]</value>
      <webElementGuid>a2120360-0ac1-4986-8035-629383f5852f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='reset your password'])[1]/following::h2[1]</value>
      <webElementGuid>a8bff949-c98e-4c7c-a612-eff418164af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter a valid email address.'])[1]/preceding::h2[1]</value>
      <webElementGuid>6203a08d-0fe4-4203-b506-9b14631eb35a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter your password.'])[1]/preceding::h2[1]</value>
      <webElementGuid>eb964430-c3a3-455c-bdbc-e42de34e7eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign in']/parent::*</value>
      <webElementGuid>22d0c536-da47-4fc2-a511-338c19aa4db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>3905b0e6-5263-4c4e-9277-883e65761c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Sign in' or . = 'Sign in')]</value>
      <webElementGuid>91718bcd-4eef-46c6-8311-33201c482f3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
