<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>68e46a7a-3690-42a0-9f5e-b368e2f16986</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Caseys Rewards logo&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@src=&quot;/_ui/responsive/common/static/images/checkout/Caseys-Rewards-Logo-Horizontal.svg&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>73503eb8-ad6e-4bc4-9254-0e00ebfad936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_ui/responsive/common/static/images/checkout/Caseys-Rewards-Logo-Horizontal.svg</value>
      <webElementGuid>29ee3e57-202c-4d7a-86a8-d7e09fc85677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Caseys Rewards logo</value>
      <webElementGuid>ea7bd49b-3a6a-4a03-98d5-179d2d7d0a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;App&quot;)/div[@class=&quot;CheckoutPage theme-light&quot;]/div[@class=&quot;full-site-width&quot;]/section[@class=&quot;Section&quot;]/div[@class=&quot;theme-light-content row&quot;]/div[@class=&quot;col-12 col-md-7 pb-3 px-lg-5 py-sm-3 py-md-5&quot;]/div[@class=&quot;CheckoutConfirmation&quot;]/div[@class=&quot;font-size-small&quot;]/div[@class=&quot;row mx-0&quot;]/div[@class=&quot;row col-sm-12 col-md-10&quot;]/div[@class=&quot;py-3 px-md-3 pl-25&quot;]/img[1]</value>
      <webElementGuid>6615f453-22b8-4850-8cd9-58e181771835</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='App']/div[3]/div/section/div/div/div/div[5]/div/div[2]/div[2]/img</value>
      <webElementGuid>d2807d8f-9aa7-4c22-afc0-76b7feabf1a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Caseys Rewards logo']</value>
      <webElementGuid>3a5adea4-0f73-4a9c-9bdb-a02bf090dfb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>b04b11ba-8778-4658-a25d-f789a04bc499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_ui/responsive/common/static/images/checkout/Caseys-Rewards-Logo-Horizontal.svg' and @alt = 'Caseys Rewards logo']</value>
      <webElementGuid>ff830941-55c2-41db-8731-e9d71327850e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
