<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subtotal</name>
   <tag></tag>
   <elementGuidId>e241d726-39cf-41e0-a2b4-ae2c2ea2c074</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*/div[contains(text(),'Subtotal')]/following::div/span)[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
